In [1]:
# 216270307034
# Siddiq Badlani

import numpy as np

a = np.array([1,2,3])
print("a:", a)

a: [1 2 3]


In [2]:
# b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[],[],[]])
b = np.arange(2, 11).reshape(3, 3)
print("b:\n", b)

b:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# a = np.append(a,[6,7,8])
print("a:\n", a)

# b = np.append(b,[10,11,12])
print("b:\n", b)

# a= np.delete(a,[4])
# b= np.delete(b,[10,11,12])

a:
 [1 2 3]
b:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
c = np.array([[1,2],[3,4],[5,6]])
print("2*3:\n\n", c)

c = c.reshape(2, 3)
print("3*2:\n\n", c)

2*3:

 [[1 2]
 [3 4]
 [5 6]]
3*2:

 [[1 2 3]
 [4 5 6]]
